(()=>{
'use strict';
const d=document,$=id=>d.getElementById(id),n=v=>Number(String(v??'').replace(/,/g,''))||0,thb=v=>n(v).toLocaleString('th-TH');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const sb=window.sb||window.supabaseClient||window.db||window.supabase;
if(!sb?.from)return;
function clientId(){return window.currentClientId||window.selectedClientId||null}
function toast(msg){try{window.toast?window.toast(msg):alert(msg)}catch{alert(msg)}}
const css=d.createElement('style');css.textContent=`
.hp-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.hp-card{background:#fff;border:1px solid #eceff3;border-radius:16px;padding:16px}.hp-k{font-size:12px;color:#737b87}.hp-v{font-size:22px;font-weight:900;margin-top:4px}.hp-gap{color:#d31145}.hp-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.hp-field label{display:block;font-size:12px;color:#6b7280;margin-bottom:5px}.hp-field input,.hp-field select,.hp-field textarea{width:100%;box-sizing:border-box;border:1px solid #dfe3e8;border-radius:10px;padding:10px;background:#fff}.hp-table{width:100%;border-collapse:collapse}.hp-table th,.hp-table td{padding:10px;border-bottom:1px solid #edf0f3;text-align:left;font-size:12px}.hp-table th{background:#fafbfc}.hp-score{font-weight:900;color:#d31145}.hp-note{background:#fff7f9;border:1px solid #f5c6d4;border-radius:12px;padding:12px;color:#6b2036}.hp-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.hp-btn{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.hp-red{background:#d31145;color:#fff}.hp-light{background:#f3f4f6;color:#222}.hp-empty{padding:20px;text-align:center;color:#707782;border:1px dashed #d5d9df;border-radius:12px}.hp-checks{display:flex;gap:14px;flex-wrap:wrap}.hp-checks label{font-size:13px}.hp-analysis{white-space:pre-line;line-height:1.6}.hp-badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#fff0f4;color:#b30f3b;font-weight:800;font-size:11px}@media(max-width:760px){.hp-grid,.hp-form{grid-template-columns:1fr}.hp-table{min-width:720px}.hp-scroll{overflow:auto}}
`;d.head.appendChild(css);
function mount(){const nav=d.querySelector('.nav'),main=d.querySelector('main.main');if(!nav||!main||$('health-planner'))return;const ref=nav.querySelector('[data-tab="policies"]')||nav.lastElementChild;const b=d.createElement('button');b.dataset.tab='health-planner';b.textContent='Health Planner';ref?.after(b)||nav.appendChild(b);const s=d.createElement('section');s.id='health-planner';s.className='section';s.innerHTML=`
<div class="top"><div><h2>Health Planner <span class="hp-badge">/AIA Analysis</span></h2><p>วิเคราะห์ความคุ้มครองสุขภาพเดิม หา Gap และเทียบแผนที่เหมาะสมจาก Product Catalog</p></div></div>
<div class="hp-grid"><div class="hp-card"><div class="hp-k">วงเงินสุขภาพเดิม</div><div class="hp-v" id="hpCurrent">0</div></div><div class="hp-card"><div class="hp-k">วงเงินเป้าหมาย</div><div class="hp-v" id="hpTargetKpi">0</div></div><div class="hp-card"><div class="hp-k">Health Coverage Gap</div><div class="hp-v hp-gap" id="hpGap">0</div></div></div>
<div class="card" style="margin-top:16px"><div class="head"><h3>1. ข้อมูลความต้องการลูกค้า</h3></div><div class="hp-form">
<div class="hp-field"><label>งบเบี้ยต่อปี</label><input id="hpBudget" inputmode="decimal" placeholder="0"></div><div class="hp-field"><label>สวัสดิการค่าห้อง/วัน</label><input id="hpEmpRoom" inputmode="decimal" placeholder="0"></div><div class="hp-field"><label>สวัสดิการวงเงินรักษา/ปี</label><input id="hpEmpAnnual" inputmode="decimal" placeholder="0"></div><div class="hp-field"><label>ค่าห้องโรงพยาบาลเป้าหมาย/วัน</label><input id="hpRoomTarget" inputmode="decimal" placeholder="0"></div><div class="hp-field"><label>วงเงินรักษาเป้าหมาย/ปี</label><input id="hpAnnualTarget" inputmode="decimal" placeholder="5000000"></div><div class="hp-field"><label>Deductible ที่รับได้</label><input id="hpDeductible" inputmode="decimal" placeholder="0"></div><div class="hp-field"><label>โรงพยาบาลที่ต้องการใช้</label><input id="hpHospital" placeholder="เช่น โรงพยาบาลเอกชน"></div><div class="hp-field" style="grid-column:span 2"><label>หมายเหตุ/ความต้องการเพิ่มเติม</label><textarea id="hpNotes" rows="2"></textarea></div></div>
<div class="hp-checks" style="margin-top:12px"><label><input id="hpOpd" type="checkbox"> ต้องการ OPD</label><label><input id="hpCancer" type="checkbox"> เน้นมะเร็ง</label><label><input id="hpCi" type="checkbox"> เน้นโรคร้ายแรง</label></div><div class="hp-actions"><button class="hp-btn hp-red" id="hpAnalyze">วิเคราะห์ด้วย /AIA</button><button class="hp-btn hp-light" id="hpSave">บันทึก Health Plan</button></div></div>
<div class="card" style="margin-top:16px"><div class="head"><h3>2. สรุป Gap</h3></div><div id="hpSummary" class="hp-note">กรอกข้อมูลและกด “วิเคราะห์ด้วย /AIA”</div></div>
<div class="card" style="margin-top:16px"><div class="head"><h3>3. ตารางเปรียบเทียบแผนสุขภาพ</h3><span id="hpCatalogCount"></span></div><div class="hp-scroll"><div id="hpCompare"></div></div></div>
<div class="card" style="margin-top:16px"><div class="head"><h3>4. คำแนะนำสำหรับนำเสนอ</h3></div><div id="hpAdvice" class="hp-analysis">ยังไม่ได้วิเคราะห์</div></div>`;main.appendChild(s);
d.addEventListener('click',e=>{const x=e.target.closest('[data-tab="health-planner"]');if(!x)return;if(!clientId()){toast('กรุณาเลือกลูกค้าก่อน');d.querySelector('[data-tab="clients"]')?.click();return}d.querySelectorAll('.nav button').forEach(q=>q.classList.toggle('active',q===x));d.querySelectorAll('.section').forEach(q=>q.classList.toggle('active',q.id==='health-planner'));if($('pageTitle'))$('pageTitle').textContent='วิเคราะห์ประกันสุขภาพ';load();});
$('hpAnalyze').onclick=analyze;$('hpSave').onclick=save;['hpBudget','hpEmpRoom','hpEmpAnnual','hpRoomTarget','hpAnnualTarget','hpDeductible'].forEach(id=>$(id).addEventListener('blur',e=>e.target.value=thb(e.target.value)));
}
let client=null,policies=[],plans=[],lastAnalysis={};
async function load(){const id=clientId();if(!id)return;const [c,p,a,h]=await Promise.all([sb.from('clients').select('*').eq('id',id).maybeSingle(),sb.from('insurance_policies').select('*').eq('client_id',id),sb.from('health_assessments').select('*').eq('client_id',id).order('updated_at',{ascending:false}).limit(1).maybeSingle(),sb.from('health_product_plans').select('*').eq('is_active',true).order('sort_order')]);if(c.error){toast('โหลดข้อมูลลูกค้าไม่สำเร็จ');return}client=c.data;policies=p.data||[];plans=h.data||[];if(a.data)fill(a.data);renderKpi();$('hpCatalogCount').textContent=`Product Catalog ${plans.length} แผน`;if(!plans.length)$('hpCompare').innerHTML='<div class="hp-empty">ยังไม่มีข้อมูลแผนสุขภาพใน Product Catalog เมื่ออัปเดตข้อมูลจาก /AIA แล้ว ระบบจะนำมาเทียบและจัดอันดับให้โดยอัตโนมัติ</div>';}
function fill(a){$('hpBudget').value=thb(a.budget_per_year);$('hpEmpRoom').value=thb(a.employer_room_limit);$('hpEmpAnnual').value=thb(a.employer_annual_limit);$('hpRoomTarget').value=thb(a.preferred_room_cost);$('hpAnnualTarget').value=thb(a.target_annual_limit);$('hpDeductible').value=thb(a.deductible_preference);$('hpHospital').value=a.hospital_preference||'';$('hpNotes').value=a.notes||'';$('hpOpd').checked=!!a.wants_opd;$('hpCancer').checked=!!a.wants_cancer_focus;$('hpCi').checked=!!a.wants_ci_focus;if(a.analysis&&Object.keys(a.analysis).length){lastAnalysis=a.analysis;renderAnalysis(a.analysis)}}
function currentHealth(){return policies.filter(p=>p.policy_status!=='cancelled'&&p.policy_status!=='lapsed').reduce((s,p)=>s+n(p.health_limit),0)}
function age(){if(!client?.birth_date)return 0;const b=new Date(client.birth_date),t=new Date();let x=t.getFullYear()-b.getFullYear();if(t<new Date(t.getFullYear(),b.getMonth(),b.getDate()))x--;return x}
function values(){return{budget:n($('hpBudget').value),empRoom:n($('hpEmpRoom').value),empAnnual:n($('hpEmpAnnual').value),roomTarget:n($('hpRoomTarget').value),annualTarget:n($('hpAnnualTarget').value)||5000000,deductible:n($('hpDeductible').value),opd:$('hpOpd').checked,cancer:$('hpCancer').checked,ci:$('hpCi').checked,hospital:$('hpHospital').value.trim(),notes:$('hpNotes').value.trim()}}
function renderKpi(){const v=values(),cur=currentHealth()+v.empAnnual,gap=Math.max(0,v.annualTarget-cur);$('hpCurrent').textContent=thb(cur);$('hpTargetKpi').textContent=thb(v.annualTarget);$('hpGap').textContent=thb(gap)}
function scorePlan(p,v,a){if(p.min_age!=null&&a&&a<n(p.min_age))return-999;if(p.max_age!=null&&a&&a>n(p.max_age))return-999;let s=0;if(n(p.annual_limit)>=v.annualTarget)s+=35;else s+=Math.min(30,n(p.annual_limit)/Math.max(v.annualTarget,1)*30);if(v.roomTarget&&n(p.room_limit)>=v.roomTarget)s+=15;if(v.deductible===n(p.deductible))s+=10;else if(v.deductible&&n(p.deductible)<=v.deductible)s+=7;if(v.opd&&n(p.opd_limit)>0)s+=10;if(v.cancer&&n(p.cancer_limit)>0)s+=10;if(v.ci&&n(p.ci_limit)>0)s+=10;if(v.budget&&p.premium_max!=null&&n(p.premium_max)<=v.budget)s+=10;return Math.round(s)}
function analyze(){renderKpi();const v=values(),cur=currentHealth()+v.empAnnual,gap=Math.max(0,v.annualTarget-cur),roomGap=Math.max(0,v.roomTarget-v.empRoom),a=age();const ranked=plans.map(p=>({...p,_score:scorePlan(p,v,a)})).filter(p=>p._score>=0).sort((x,y)=>y._score-x._score);const top=ranked.slice(0,5);let reason=gap>0?`วงเงินรักษารวมปัจจุบันประมาณ ${thb(cur)} บาท/ปี ต่ำกว่าเป้าหมาย ${thb(v.annualTarget)} บาท จึงมี Gap ประมาณ ${thb(gap)} บาท/ปี`:`วงเงินรักษารวมปัจจุบันครอบคลุมเป้าหมายที่กำหนดแล้ว`;if(roomGap>0)reason+=` และค่าห้องยังมีส่วนต่างประมาณ ${thb(roomGap)} บาท/วัน`;if(v.budget)reason+=` โดยมีงบเบี้ยประมาณ ${thb(v.budget)} บาท/ปี`;lastAnalysis={generated_at:new Date().toISOString(),current_health:cur,target_annual_limit:v.annualTarget,gap,room_gap:roomGap,age:a,ranked:top.map(p=>({id:p.id,product_name:p.product_name,plan_name:p.plan_name,score:p._score})),summary:reason};renderAnalysis(lastAnalysis,ranked)}
function renderAnalysis(a,rankedOverride){$('hpSummary').textContent=a.summary||'ไม่มีข้อมูล';const ranked=rankedOverride||plans.map(p=>{const r=(a.ranked||[]).find(x=>x.id===p.id);return r?{...p,_score:r.score}:null}).filter(Boolean).sort((x,y)=>y._score-x._score);if(ranked.length){$('hpCompare').innerHTML=`<table class="hp-table"><thead><tr><th>แผน</th><th>ค่าห้อง/วัน</th><th>วงเงิน/ปี</th><th>Deductible</th><th>OPD</th><th>Cancer</th><th>ช่วงเบี้ย</th><th>คะแนนเหมาะสม</th></tr></thead><tbody>${ranked.slice(0,5).map(p=>`<tr><td><b>${esc(p.product_name)}</b><br>${esc(p.plan_name)}</td><td>${thb(p.room_limit)}</td><td>${thb(p.annual_limit)}</td><td>${thb(p.deductible)}</td><td>${n(p.opd_limit)?thb(p.opd_limit):'-'}</td><td>${n(p.cancer_limit)?thb(p.cancer_limit):'-'}</td><td>${p.premium_min!=null||p.premium_max!=null?`${thb(p.premium_min)}–${thb(p.premium_max)}`:'-'}</td><td class="hp-score">${p._score}/100</td></tr>`).join('')}</tbody></table>`;const best=ranked[0];$('hpAdvice').textContent=`แผนที่ควรพิจารณาเป็นอันดับแรก: ${best.product_name} ${best.plan_name}\nเหตุผล: คะแนนความเหมาะสม ${best._score}/100 จากวงเงินเป้าหมาย งบประมาณ ความต้องการ OPD/มะเร็ง/โรคร้ายแรง และ Deductible ที่ลูกค้ารับได้\n\n${best.key_reasons||best.suitable_for||''}\n\nหมายเหตุ: ผลนี้เป็นเครื่องมือช่วยวิเคราะห์เบื้องต้น ต้องตรวจสอบเงื่อนไขรับประกัน ข้อยกเว้น เบี้ยจริง และเอกสารผลิตภัณฑ์ล่าสุดก่อนนำเสนอ`;}
else{$('hpCompare').innerHTML='<div class="hp-empty">ยังไม่มีแผนที่สามารถนำมาเปรียบเทียบได้ กรุณาอัปเดต Product Catalog จากข้อมูล /AIA</div>';$('hpAdvice').textContent=`${a.summary||''}\n\nระบบหา Gap ให้แล้ว แต่ยังไม่มีข้อมูล Product Catalog สำหรับระบุชื่อแผนที่เหมาะสม จึงยังไม่เดาชื่อผลิตภัณฑ์เพื่อป้องกันคำแนะนำผิด`}}
async function save(){const id=clientId();if(!id)return;const v=values();const {data:{user}}=await sb.auth.getUser();if(!user){toast('กรุณาเข้าสู่ระบบ');return}const payload={client_id:id,advisor_id:user.id,insured_name:client?.full_name||'',budget_per_year:v.budget,employer_room_limit:v.empRoom,employer_annual_limit:v.empAnnual,preferred_room_cost:v.roomTarget,target_annual_limit:v.annualTarget,deductible_preference:v.deductible,wants_opd:v.opd,wants_cancer_focus:v.cancer,wants_ci_focus:v.ci,hospital_preference:v.hospital,notes:v.notes,analysis:lastAnalysis,updated_at:new Date().toISOString()};const {data:old}=await sb.from('health_assessments').select('id').eq('client_id',id).eq('advisor_id',user.id).limit(1).maybeSingle();let q=old?.id?sb.from('health_assessments').update(payload).eq('id',old.id):sb.from('health_assessments').insert(payload);const {error}=await q;if(error)toast('บันทึกไม่สำเร็จ: '+error.message);else toast('บันทึก Health Planner แล้ว')}
let tries=0;const timer=setInterval(()=>{tries++;if(d.querySelector('.nav')&&d.querySelector('main.main')){clearInterval(timer);mount()}else if(tries>40)clearInterval(timer)},250);
})();