(()=>{
const addStyle=document.createElement('style');addStyle.textContent=`.searchbox{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:10px;margin-bottom:12px}.toolrow{display:flex;gap:8px;flex-wrap:wrap}.danger{background:#fff;border:1px solid #fecaca;color:#b91c1c}.history-item{padding:10px 0;border-bottom:1px solid var(--line)}.history-time{font-size:10px;color:var(--muted)}.linkbox{word-break:break-all;background:#f9fafb;border:1px dashed #d1d5db;padding:10px;border-radius:10px;font-size:11px;margin-top:8px}.intake-overlay{position:fixed;inset:0;z-index:10001;background:#f7f8fa;display:none;overflow:auto;padding:20px}.intake-card{width:min(720px,100%);margin:20px auto;background:#fff;border:1px solid var(--line);border-radius:22px;box-shadow:var(--shadow);padding:22px}`;document.head.appendChild(addStyle);
let allClients=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const clientsSection=document.getElementById('clients');
if(clientsSection){const list=document.getElementById('clientList');if(list){const search=document.createElement('input');search.id='clientSearch';search.className='searchbox';search.placeholder='ค้นหาชื่อ เบอร์ อีเมล หรืออาชีพ';search.oninput=()=>renderClientList();list.parentNode.insertBefore(search,list);const tools=document.createElement('div');tools.id='clientTools';tools.style.cssText='display:none;margin-top:16px;border-top:1px solid var(--line);padding-top:14px';tools.innerHTML=`<div class="head"><h3>เครื่องมือลูกค้าปัจจุบัน</h3><span id="selectedClientLabel"></span></div><div class="toolrow"><button class="btn light" onclick="generateClientLink()">สร้าง Client Link</button><button class="btn light" onclick="saveRecommendationSnapshot()">บันทึก Recommendation ครั้งนี้</button><button class="btn light" onclick="loadClientHistory()">ดูประวัติ</button><button class="btn danger" onclick="deleteCurrentClient()">ลบลูกค้า</button></div><div id="clientLinkBox" class="linkbox" style="display:none"></div><div id="clientHistory" style="margin-top:12px"></div>`;list.parentNode.appendChild(tools)}}
window.renderClientList=function(){const q=(document.getElementById('clientSearch')?.value||'').trim().toLowerCase();const data=allClients.filter(c=>[c.full_name,c.nickname,c.phone,c.email,c.occupation].some(v=>String(v||'').toLowerCase().includes(q)));document.getElementById('clientCount').textContent=data.length+(q?' รายที่พบ':' ราย');document.getElementById('clientList').innerHTML=data.length?data.map(c=>`<div class="client-item ${c.id===currentClientId?'active':''}" onclick="openClient('${c.id}')"><div><b>${esc(c.full_name)}</b>${c.nickname?` <span class="mini">(${esc(c.nickname)})</span>`:''}<div class="client-meta">${esc(c.phone||c.email||c.occupation||'ยังไม่มีข้อมูลติดต่อ')}</div></div><span class="tag">เปิด</span></div>`).join(''):'<div class="mini">ไม่พบข้อมูลลูกค้า</div>';updateClientTools()};
window.updateClientTools=function(){const c=allClients.find(x=>x.id===currentClientId),t=document.getElementById('clientTools');if(!t)return;t.style.display=c?'block':'none';document.getElementById('selectedClientLabel').textContent=c?c.full_name:''};
window.loadClients=async function(){const {data,error}=await sb.from('clients').select('id,full_name,nickname,phone,email,occupation,updated_at,created_at').order('updated_at',{ascending:false});if(error){toast('โหลดรายชื่อลูกค้าไม่สำเร็จ: '+error.message);return}allClients=data||[];renderClientList()};
const oldCreate=window.createClient;window.createClient=async function(){await oldCreate();if(currentClientId)await sb.from('client_history').insert({client_id:currentClientId,event_type:'create',summary:'สร้างโปรไฟล์ลูกค้า',snapshot:snapshotPlanner()});await loadClients()};
const oldSave=window.saveCurrentClient;window.saveCurrentClient=async function(){await oldSave();if(currentClientId)await sb.from('client_history').insert({client_id:currentClientId,event_type:'save',summary:'บันทึกข้อมูลและผลวิเคราะห์',snapshot:snapshotPlanner()});await loadClients()};
const oldOpen=window.openClient;window.openClient=async function(id){await oldOpen(id);updateClientTools()};
window.deleteCurrentClient=async function(){if(!currentClientId)return;const c=allClients.find(x=>x.id===currentClientId);if(!confirm(`ยืนยันลบข้อมูลลูกค้า ${c?.full_name||''} ? การลบนี้ย้อนกลับไม่ได้`))return;const {error}=await sb.from('clients').delete().eq('id',currentClientId);if(error){toast('ลบไม่สำเร็จ: '+error.message);return}currentClientId=null;resetDemo();await loadClients();toast('ลบข้อมูลลูกค้าแล้ว')};
window.loadClientHistory=async function(){if(!currentClientId)return;const [{data:h,error},{data:r}]=await Promise.all([sb.from('client_history').select('event_type,summary,created_at').eq('client_id',currentClientId).order('created_at',{ascending:false}).limit(20),sb.from('recommendations').select('product_name,category,created_at').eq('client_id',currentClientId).order('created_at',{ascending:false}).limit(20)]);if(error){toast(error.message);return}const entries=[...(h||[]),...(r||[]).map(x=>({summary:`Recommendation: ${x.product_name}`,event_type:x.category,created_at:x.created_at}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,25);document.getElementById('clientHistory').innerHTML='<b style="font-size:12px">ประวัติล่าสุด</b>'+(entries.length?entries.map(x=>`<div class="history-item"><b style="font-size:12px">${esc(x.summary||x.event_type)}</b><div class="history-time">${new Date(x.created_at).toLocaleString('th-TH')}</div></div>`).join(''):'<div class="mini" style="margin-top:8px">ยังไม่มีประวัติ</div>')};
window.saveRecommendationSnapshot=async function(){if(!currentClientId){toast('กรุณาเลือกลูกค้าก่อน');return}const cards=[...document.querySelectorAll('#productRecommendations .prod')];if(!cards.length){toast('ยังไม่มี Product Recommendation ให้บันทึก');return}const batch=crypto.randomUUID(),rows=cards.map((card,i)=>({client_id:currentClientId,category:card.querySelector('.tag')?.textContent?.trim()||'planning',product_name:card.querySelector('h4')?.textContent?.trim()||'AIA Recommendation',rationale:card.querySelector('.why')?.textContent?.trim()||card.textContent.trim(),priority:Math.min(5,i+1),status:'snapshot',snapshot:{batch_id:batch,planner:snapshotPlanner()}}));const {error}=await sb.from('recommendations').insert(rows);if(error){toast('บันทึก Recommendation ไม่สำเร็จ: '+error.message);return}await sb.from('client_history').insert({client_id:currentClientId,event_type:'recommendation',summary:`บันทึก Recommendation ${rows.length} รายการ`,snapshot:{batch_id:batch,products:rows.map(x=>x.product_name)}});toast('บันทึก Recommendation ครั้งนี้แล้ว');loadClientHistory()};
const randomToken=()=>{const a=new Uint8Array(24);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const sha256Hex=async t=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
window.generateClientLink=async function(){if(!currentClientId){toast('กรุณาเลือกลูกค้าก่อน');return}const token=randomToken(),hash=await sha256Hex(token);await sb.from('client_intake_links').update({is_active:false}).eq('client_id',currentClientId).eq('is_active',true);const {error}=await sb.from('client_intake_links').insert({client_id:currentClientId,token_hash:hash,expires_at:new Date(Date.now()+7*86400000).toISOString()});if(error){toast('สร้างลิงก์ไม่สำเร็จ: '+error.message);return}const link=`${location.origin}${location.pathname}?intake=${encodeURIComponent(token)}`,box=document.getElementById('clientLinkBox');box.style.display='block';box.innerHTML=`<b>Client Link (ใช้ได้ 7 วัน)</b><br>${esc(link)}<div class="actions" style="margin-top:8px"><button class="btn light" id="copyClientLink">คัดลอกลิงก์</button></div>`;document.getElementById('copyClientLink').onclick=async()=>{try{await navigator.clipboard.writeText(link);toast('คัดลอกลิงก์แล้ว')}catch(e){prompt('คัดลอกลิงก์นี้',link)}};toast('สร้าง Client Link แล้ว')};
const intake=document.createElement('div');intake.id='intakeOverlay';intake.className='intake-overlay';intake.innerHTML=`<div class="intake-card"><div class="brand"><div class="mark">AIA</div><div><h1>Financial Planning Intake</h1><p>แบบฟอร์มข้อมูลสำหรับการวางแผน</p></div></div><h2 id="intakeTitle">แบบฟอร์มข้อมูลลูกค้า</h2><div class="notice">ข้อมูลนี้จะส่งตรงถึงที่ปรึกษาที่สร้างลิงก์นี้ และไม่แสดงข้อมูลลูกค้ารายอื่น</div><div class="formgrid" id="intakeFields"></div><div class="actions" style="margin-top:16px"><button class="btn red" id="submitIntakeBtn">ส่งข้อมูลให้ที่ปรึกษา</button></div><div id="intakeStatus" class="notice"></div></div>`;document.body.appendChild(intake);
const fields=[['name','ชื่อ-นามสกุล','text'],['age','อายุ','number'],['dependents','ผู้ที่ต้องดูแลทางการเงิน (คน)','number'],['income','รายได้ต่อเดือน','number'],['saving','เงินออม/ลงทุนต่อเดือน','number'],['expense','รายจ่ายต่อเดือน','number'],['debtPay','ยอดผ่อนหนี้ต่อเดือน','number'],['lifeCover','ทุนประกันชีวิตที่มีอยู่','number'],['healthBenefit','วงเงินสุขภาพที่มีอยู่','number'],['premiumBudget','งบประมาณเบี้ยที่สะดวก/ปี','number'],['retireAge','อายุที่ต้องการเกษียณ','number'],['legacyGoal','เป้าหมายมรดก','number']];document.getElementById('intakeFields').innerHTML=fields.map(([k,l,t])=>`<div class="field"><label>${l}</label><input id="i_${k}" type="${t}"></div>`).join('');
let intakeToken=null;async function loadIntake(token){intakeToken=token;document.getElementById('authOverlay').style.display='none';document.querySelector('.app').style.display='none';intake.style.display='block';const {data,error}=await sb.rpc('get_client_intake',{p_token:token}),row=Array.isArray(data)?data[0]:data;if(error||!row){document.getElementById('intakeStatus').textContent='ลิงก์นี้ไม่ถูกต้อง หมดอายุ หรือถูกยกเลิกแล้ว';return}const d=row.planner_data||{};document.getElementById('intakeTitle').textContent=`แบบฟอร์มสำหรับ ${row.full_name||'ลูกค้า'}`;fields.forEach(([k])=>document.getElementById('i_'+k).value=d[k]??'')}
document.getElementById('submitIntakeBtn').onclick=async()=>{const d={};fields.forEach(([k])=>d[k]=document.getElementById('i_'+k).value);const {data,error}=await sb.rpc('submit_client_intake',{p_token:intakeToken,p_data:d});document.getElementById('intakeStatus').textContent=error?'ส่งข้อมูลไม่สำเร็จ: '+error.message:(data?'ส่งข้อมูลเรียบร้อยแล้ว ที่ปรึกษาจะได้รับข้อมูลล่าสุด':'ลิงก์หมดอายุหรือถูกยกเลิกแล้ว');if(data)document.getElementById('submitIntakeBtn').disabled=true};
const token=new URLSearchParams(location.search).get('intake');if(token)loadIntake(token);else loadClients();
})();