(()=>{
'use strict';
const d=document,$=id=>d.getElementById(id),money=v=>Number(v||0).toLocaleString('th-TH')+' บาท',num=v=>Number(String(v??'').replace(/,/g,''))||0;
const products=['เลือกแบบประกัน','AIA Life Protector 70','AIA Pay Life Plus 10/15/20','AIA Health Happy','AIA CI Plus','AIA CI Top Up','AIA Annuity Fix','AIA Issara Plus','AIA Smart Select','AIA Prestige'];
let policies=[],activePolicy=-1,ocrFile=null;
const css=d.createElement('style');css.textContent=`
.policy-toolbar{display:flex;gap:8px;flex-wrap:wrap}.policy-toolbar .btn{display:inline-flex;align-items:center;gap:7px}
.policy-empty{padding:28px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}
.policy-list{display:flex;gap:8px;overflow:auto;padding-bottom:8px}.policy-chip{white-space:nowrap;border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 12px;cursor:pointer}.policy-chip.active{background:var(--pink);border-color:#e68aa5;color:var(--red);font-weight:800}
.policy-chart-wrap{overflow-x:auto;border:1px solid var(--line);border-radius:14px;background:#fff}.policy-chart-wrap canvas{display:block;min-height:430px}
.policy-table-wrap{overflow:auto;max-height:520px}.policy-table input{width:112px;border:1px solid #d9dde5;border-radius:8px;padding:8px;text-align:right}.policy-table input.age{width:68px}
.policy-status{font-size:12px;color:var(--muted);margin-top:8px}.policy-status.ok{color:#087449}.policy-status.bad{color:#b91c1c}
.policy-file-card{border:1px dashed #e68aa5;background:#fff7f9;border-radius:14px;padding:14px}.policy-kpis{grid-template-columns:repeat(4,minmax(0,1fr))}
@media(max-width:680px){.policy-kpis{grid-template-columns:1fr 1fr}.policy-toolbar .btn{flex:1;justify-content:center}.policy-table input{width:96px}}
`;d.head.appendChild(css);

function mount(){
 const risk=d.querySelector('[data-tab="risk"]'),nav=d.querySelector('.nav');if(!nav||$('policies'))return;
 const b=d.createElement('button');b.dataset.tab='policies';b.textContent='กรมธรรม์';risk?.after(b)||nav.appendChild(b);
 const sec=d.createElement('section');sec.id='policies';sec.className='section';sec.innerHTML=`
 <div class="card"><div class="head"><div><h3>กรมธรรม์ของลูกค้า</h3><span>Policy Portfolio</span></div><div class="policy-toolbar"><button class="btn red" id="policyNewBtn">＋ เพิ่มกรมธรรม์</button><button class="btn light" id="policyCameraBtn">📷 ถ่ายรูปกรมธรรม์</button><button class="btn light" id="policyUploadBtn">📄 อัปโหลดเอกสาร</button><button class="btn light" id="policyPdfBtn">ส่งออกรายงาน PDF</button></div></div>
 <input id="policyCameraInput" type="file" accept="image/*" capture="environment" hidden><input id="policyUploadInput" type="file" accept="image/jpeg,image/png,application/pdf" hidden>
 <div class="policy-file-card"><b>นำเข้าข้อมูลอัตโนมัติ</b><div class="notice">“ถ่ายรูป” จะเปิดกล้องและขอสิทธิ์จากอุปกรณ์ ส่วน “อัปโหลดเอกสาร” จะเปิดพื้นที่จัดเก็บไฟล์ รองรับ JPG, PNG และ PDF</div><div id="policyImportStatus" class="policy-status">ยังไม่ได้เลือกเอกสาร</div></div>
 <div id="policyList" class="policy-list" style="margin-top:14px"></div></div>
 <div id="policyEditor" style="display:none">
  <div class="card" style="margin-top:16px"><div class="head"><h3>รายละเอียดกรมธรรม์</h3><button class="btn danger" id="policyDeleteBtn">ลบกรมธรรม์นี้</button></div><div class="formgrid">
   <div class="field"><label>ชื่อแบบประกัน</label><select id="polProduct">${products.map(x=>`<option>${x}</option>`).join('')}</select></div>
   <div class="field"><label>เลขที่กรมธรรม์</label><input id="polNumber" placeholder="กรอกเลขที่กรมธรรม์"></div>
   <div class="field"><label>ชื่อผู้เอาประกัน</label><input id="polInsured"></div><div class="field"><label>อายุเริ่มทำประกัน</label><input id="polStartAge" type="number" min="0" max="100"></div>
   <div class="field"><label>ระยะเวลาคุ้มครอง (ปี)</label><input id="polTerm" type="number" min="1" value="20"></div><div class="field"><label>ระยะเวลาชำระเบี้ย (ปี)</label><input id="polPayYears" type="number" min="0" value="10"></div>
   <div class="field"><label>เบี้ยประกันต่อปี</label><input id="polPremium" inputmode="decimal" placeholder="0"></div><div class="field"><label>ทุนประกันชีวิต</label><input id="polSum" inputmode="decimal" placeholder="0"></div>
   <div class="field"><label>เงินคืนระหว่างสัญญาต่อปี</label><input id="polCashback" inputmode="decimal" placeholder="0"></div><div class="field"><label>เงินคืนเมื่อครบกำหนด</label><input id="polMaturity" inputmode="decimal" placeholder="0"></div>
  </div><div class="actions" style="margin-top:14px"><button class="btn red" id="policyGenerateBtn">สร้าง/ปรับตารางรายปี</button><button class="btn light" id="policySaveBtn">บันทึกกรมธรรม์</button></div><div id="policySaveStatus" class="policy-status"></div></div>
  <div class="grid policy-kpis" style="margin-top:16px"><div class="card kpi"><div class="label">เบี้ยรวม</div><div class="value" id="pkPremium">0 บาท</div></div><div class="card kpi"><div class="label">เงินคืนระหว่างปีรวม</div><div class="value" id="pkCashback">0 บาท</div></div><div class="card kpi"><div class="label">เงินคืนครบกำหนด</div><div class="value" id="pkMaturity">0 บาท</div></div><div class="card kpi"><div class="label">ทุนชีวิตสูงสุด</div><div class="value" id="pkSum">0 บาท</div></div></div>
  <div class="card" style="margin-top:16px"><div class="head"><h3>กระแสเงินตามอายุลูกค้า</h3><span>แกนตั้ง: มูลค่าทุนชีวิตและผลประโยชน์ (บาท) • แกนนอน: อายุทุกปี</span></div><div class="policy-chart-wrap"><canvas id="policyChart" height="430"></canvas></div><div class="legend">■ สีแดง เบี้ยประกัน • ■ สีเขียว เงินคืนระหว่างปี • ■ สีทอง เงินคืนครบกำหนด • ━ สีน้ำเงิน ทุนชีวิต</div></div>
  <div class="card" style="margin-top:16px"><div class="head"><h3>ตารางรายละเอียดรายปี</h3><span>แก้ไขตัวเลขแต่ละปีได้</span></div><div class="policy-table-wrap"><table class="table policy-table"><thead><tr><th>อายุ</th><th>เบี้ยประกัน</th><th>เงินคืนระหว่างปี</th><th>เงินคืนครบกำหนด</th><th>ทุนชีวิต</th></tr></thead><tbody id="policyRows"></tbody></table></div></div>
 </div>`;
 d.querySelector('main.main').appendChild(sec);bind();loadProductCatalog();
}
function bind(){
 d.addEventListener('click',e=>{const b=e.target.closest('[data-tab="policies"]');if(!b)return;if(!currentClientId){toast('กรุณาเลือกลูกค้าก่อน');d.querySelector('[data-tab="clients"]').click();return}d.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));d.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id==='policies'));$('pageTitle').textContent='สรุปกรมธรรม์ลูกค้า';loadPolicies();});
 $('policyNewBtn').onclick=newPolicy;$('policyCameraBtn').onclick=()=>$('policyCameraInput').click();$('policyUploadBtn').onclick=()=>$('policyUploadInput').click();
 $('policyCameraInput').onchange=e=>importFile(e.target.files[0]);$('policyUploadInput').onchange=e=>importFile(e.target.files[0]);
 $('policyGenerateBtn').onclick=generateRows;$('policySaveBtn').onclick=savePolicies;$('policyDeleteBtn').onclick=deletePolicy;$('policyPdfBtn').onclick=exportPdf;
 ['polPremium','polSum','polCashback','polMaturity'].forEach(id=>$(id).addEventListener('blur',e=>{e.target.value=num(e.target.value).toLocaleString('th-TH')}));
}
async function loadProductCatalog(){try{const {data}=await sb.from('product_catalog').select('name').eq('is_active',true).order('name');const s=$('polProduct');(data||[]).forEach(x=>{if(![...s.options].some(o=>o.value===x.name))s.add(new Option(x.name,x.name))});}catch(e){}
}
function blankPolicy(){return{id:crypto.randomUUID(),product:'เลือกแบบประกัน',number:'',insured:$('name')?.value||'',startAge:num($('age')?.value)||35,term:20,payYears:10,premium:0,sumAssured:0,cashback:0,maturity:0,years:[]}}
function newPolicy(){if(!currentClientId){toast('กรุณาเลือกลูกค้าก่อน');return}policies.push(blankPolicy());activePolicy=policies.length-1;renderList();renderEditor()}
function renderList(){$('policyList').innerHTML=policies.length?policies.map((p,i)=>`<button class="policy-chip ${i===activePolicy?'active':''}" data-pi="${i}">${escapeHtml(p.product==='เลือกแบบประกัน'?'กรมธรรม์ใหม่':p.product)}${p.number?' • '+escapeHtml(p.number):''}</button>`).join(''):'<div class="policy-empty" style="width:100%">ยังไม่มีกรมธรรม์ของลูกค้ารายนี้ กด “เพิ่มกรมธรรม์” หรือใช้กล้อง/อัปโหลดเอกสารเพื่อเริ่มต้น</div>';d.querySelectorAll('[data-pi]').forEach(b=>b.onclick=()=>{activePolicy=Number(b.dataset.pi);renderList();renderEditor()})}
function renderEditor(){const p=policies[activePolicy];$('policyEditor').style.display=p?'block':'none';if(!p)return;$('polProduct').value=p.product||'เลือกแบบประกัน';$('polNumber').value=p.number||'';$('polInsured').value=p.insured||'';$('polStartAge').value=p.startAge??'';$('polTerm').value=p.term??'';$('polPayYears').value=p.payYears??'';$('polPremium').value=num(p.premium).toLocaleString('th-TH');$('polSum').value=num(p.sumAssured).toLocaleString('th-TH');$('polCashback').value=num(p.cashback).toLocaleString('th-TH');$('polMaturity').value=num(p.maturity).toLocaleString('th-TH');renderRows()}
function readForm(){const p=policies[activePolicy];if(!p)return;p.product=$('polProduct').value;p.number=$('polNumber').value.trim();p.insured=$('polInsured').value.trim();p.startAge=num($('polStartAge').value);p.term=Math.max(1,num($('polTerm').value));p.payYears=num($('polPayYears').value);p.premium=num($('polPremium').value);p.sumAssured=num($('polSum').value);p.cashback=num($('polCashback').value);p.maturity=num($('polMaturity').value)}
function generateRows(){readForm();const p=policies[activePolicy],old=new Map((p.years||[]).map(x=>[Number(x.age),x]));p.years=[];for(let i=0;i<=p.term;i++){const age=p.startAge+i,o=old.get(age);p.years.push(o||{age,premium:i<p.payYears?p.premium:0,cashback:i>0&&i<p.term?p.cashback:0,maturity:i===p.term?p.maturity:0,sumAssured:p.sumAssured})}renderRows();renderList()}
function renderRows(){const p=policies[activePolicy];if(!p)return;if(!p.years?.length)generateRows();$('policyRows').innerHTML=p.years.map((r,i)=>`<tr><td><input class="age" data-r="${i}" data-k="age" value="${r.age}"></td><td><input data-r="${i}" data-k="premium" value="${num(r.premium).toLocaleString('th-TH')}"></td><td><input data-r="${i}" data-k="cashback" value="${num(r.cashback).toLocaleString('th-TH')}"></td><td><input data-r="${i}" data-k="maturity" value="${num(r.maturity).toLocaleString('th-TH')}"></td><td><input data-r="${i}" data-k="sumAssured" value="${num(r.sumAssured).toLocaleString('th-TH')}"></td></tr>`).join('');$('policyRows').querySelectorAll('input').forEach(x=>x.onchange=()=>{p.years[Number(x.dataset.r)][x.dataset.k]=num(x.value);x.value=num(x.value).toLocaleString('th-TH');updateSummary()});updateSummary()}
function updateSummary(){const p=policies[activePolicy],ys=p?.years||[];$('pkPremium').textContent=money(ys.reduce((a,x)=>a+num(x.premium),0));$('pkCashback').textContent=money(ys.reduce((a,x)=>a+num(x.cashback),0));$('pkMaturity').textContent=money(ys.reduce((a,x)=>a+num(x.maturity),0));$('pkSum').textContent=money(Math.max(0,...ys.map(x=>num(x.sumAssured))));drawChart()}
function drawChart(){const p=policies[activePolicy],rows=p?.years||[],c=$('policyChart');if(!c||!rows.length)return;const ratio=window.devicePixelRatio||1,w=Math.max(c.parentElement.clientWidth-2,rows.length*70+90),h=430;c.style.width=w+'px';c.style.height=h+'px';c.width=w*ratio;c.height=h*ratio;const x=c.getContext('2d');x.scale(ratio,ratio);x.clearRect(0,0,w,h);const pad={l:78,r:24,t:45,b:65},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(1,...rows.flatMap(r=>[num(r.premium),num(r.cashback),num(r.maturity),num(r.sumAssured)]))*1.14,step=cw/rows.length,y=v=>pad.t+ch-(num(v)/max)*ch;
 x.font='11px system-ui';x.fillStyle='#6b7280';x.textAlign='right';for(let i=0;i<=5;i++){const val=max*i/5,yy=pad.t+ch-ch*i/5;x.strokeStyle='#eef0f3';x.beginPath();x.moveTo(pad.l,yy);x.lineTo(w-pad.r,yy);x.stroke();x.fillText(Math.round(val).toLocaleString('th-TH'),pad.l-8,yy+4)}
 const series=[['premium','#d31145'],['cashback','#16a34a'],['maturity','#d59a00']];rows.forEach((r,i)=>{const cx=pad.l+step*(i+.5),vals=series.filter(([k])=>num(r[k])>0);vals.forEach(([k,color],j)=>{const bw=Math.min(16,step/(vals.length+1)),xx=cx-(vals.length*bw)/2+j*bw,yy=y(r[k]);x.fillStyle=color;x.fillRect(xx,yy,bw-2,pad.t+ch-yy);x.save();x.translate(xx+bw/2,Math.max(14,yy-7-(j%2)*16));x.rotate(-Math.PI/2);x.fillStyle='#222';x.font='700 10px system-ui';x.textAlign='left';x.fillText(money(r[k]),0,0);x.restore()});x.fillStyle='#4b5563';x.font='11px system-ui';x.textAlign='center';x.fillText(r.age,cx,pad.t+ch+20)});
 x.strokeStyle='#2463eb';x.lineWidth=3;x.beginPath();rows.forEach((r,i)=>{const cx=pad.l+step*(i+.5),yy=y(r.sumAssured);i?x.lineTo(cx,yy):x.moveTo(cx,yy)});x.stroke();rows.forEach((r,i)=>{const cx=pad.l+step*(i+.5),yy=y(r.sumAssured);x.fillStyle='#2463eb';x.beginPath();x.arc(cx,yy,4,0,Math.PI*2);x.fill();if(i===0||i===rows.length-1||num(r.sumAssured)!==num(rows[i-1]?.sumAssured)){x.font='700 10px system-ui';x.textAlign='center';x.fillText(money(r.sumAssured),cx,Math.max(14,yy-10))}});x.fillStyle='#111827';x.font='700 12px system-ui';x.save();x.translate(18,pad.t+ch/2);x.rotate(-Math.PI/2);x.textAlign='center';x.fillText('มูลค่าทุนชีวิตและผลประโยชน์ (บาท)',0,0);x.restore();x.textAlign='center';x.fillText('อายุลูกค้า (ปี)',pad.l+cw/2,h-12)
}
async function loadPolicies(){if(!currentClientId)return;activePolicy=-1;policies=[];try{const {data,error}=await sb.from('financial_profiles').select('planner_data').eq('client_id',currentClientId).maybeSingle();if(error)throw error;policies=Array.isArray(data?.planner_data?.policyPortfolio)?data.planner_data.policyPortfolio:[];activePolicy=policies.length?0:-1;renderList();renderEditor()}catch(e){toast('โหลดกรมธรรม์ไม่สำเร็จ: '+e.message)}}
async function savePolicies(){readForm();const status=$('policySaveStatus');status.textContent='กำลังบันทึก...';status.className='policy-status';try{const {data,error}=await sb.from('financial_profiles').select('planner_data').eq('client_id',currentClientId).maybeSingle();if(error)throw error;const planner={...(data?.planner_data||{}),policyPortfolio:policies};const {error:e}=await sb.from('financial_profiles').upsert({client_id:currentClientId,planner_data:planner},{onConflict:'client_id'});if(e)throw e;status.textContent='บันทึกกรมธรรม์ในบัญชีเรียบร้อย';status.className='policy-status ok';renderList();toast('บันทึกกรมธรรม์แล้ว')}catch(e){status.textContent='บันทึกไม่สำเร็จ: '+e.message;status.className='policy-status bad'}}
function deletePolicy(){if(activePolicy<0||!confirm('ยืนยันลบกรมธรรม์นี้?'))return;policies.splice(activePolicy,1);activePolicy=Math.min(activePolicy,policies.length-1);renderList();renderEditor();savePolicies()}
async function importFile(file){if(!file)return;ocrFile=file;if(!currentClientId){toast('กรุณาเลือกลูกค้าก่อน');return}if(activePolicy<0)newPolicy();const st=$('policyImportStatus');st.textContent=`เลือก ${file.name} แล้ว • กำลังอ่านข้อมูล...`;st.className='policy-status';try{let text='';if(file.type==='application/pdf')text=await readPdf(file);else text=await readImage(file);applyOcr(text);st.textContent=`อ่าน ${file.name} แล้ว กรุณาตรวจสอบข้อมูลก่อนบันทึก`;st.className='policy-status ok'}catch(e){st.textContent=`เลือก ${file.name} แล้ว แต่ระบบอ่านอัตโนมัติไม่สำเร็จ กรุณากรอกข้อมูลในแบบฟอร์มด้านล่าง`;st.className='policy-status bad';console.warn(e)}}
function loadScript(src,id){return new Promise((res,rej)=>{if($(id))return res();const s=d.createElement('script');s.id=id;s.src=src;s.onload=res;s.onerror=rej;d.head.appendChild(s)})}
async function readImage(file){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js','tesseractLib');const r=await Tesseract.recognize(file,'tha+eng',{logger:m=>{if(m.status==='recognizing text')$('policyImportStatus').textContent=`กำลังอ่านข้อความ ${Math.round((m.progress||0)*100)}%`}});return r.data.text||''}
async function readPdf(file){await loadScript('https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js','pdfjsLib');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';for(let i=1;i<=Math.min(3,pdf.numPages);i++){const page=await pdf.getPage(i),txt=await page.getTextContent();out+=' '+txt.items.map(x=>x.str).join(' ')}return out}
function pick(text,patterns){for(const p of patterns){const m=text.match(p);if(m)return m[1].trim()}return''}
function applyOcr(text){const p=policies[activePolicy];p.insured=pick(text,[/ชื่อผู้เอาประกัน(?:ภัย)?\s*[:：]?\s*([^\n]{3,60})/i,/ผู้เอาประกัน(?:ภัย)?\s*[:：]?\s*([^\n]{3,60})/i])||p.insured;p.number=pick(text,[/เลขที่กรมธรรม์\s*[:：]?\s*([A-Z0-9\/-]+)/i,/Policy\s*No\.?\s*[:：]?\s*([A-Z0-9\/-]+)/i])||p.number;const premium=pick(text,[/เบี้ยประกัน(?:ภัย)?(?:รายปี|ต่อปี)?\s*[:：]?\s*([\d,]+)/i]),sum=pick(text,[/ทุนประกัน(?:ชีวิต)?\s*[:：]?\s*([\d,]+)/i]);if(premium)p.premium=num(premium);if(sum)p.sumAssured=num(sum);for(const name of [...$('polProduct').options].map(o=>o.value))if(name!=='เลือกแบบประกัน'&&text.toLowerCase().includes(name.toLowerCase()))p.product=name;renderEditor()}
function exportPdf(){const p=policies[activePolicy];if(!p){toast('กรุณาเลือกกรมธรรม์ก่อน');return}readForm();drawChart();const img=$('policyChart').toDataURL('image/png'),ys=p.years||[],total=k=>ys.reduce((a,x)=>a+num(x[k]),0),w=window.open('','_blank');if(!w){toast('กรุณาอนุญาต Pop-up เพื่อสร้าง PDF');return}w.document.write(`<!doctype html><html lang="th"><head><meta charset="utf-8"><title>รายงานกรมธรรม์</title><style>body{font-family:system-ui,'Noto Sans Thai',sans-serif;color:#171717;margin:0}.page{padding:14mm}.head{display:flex;justify-content:space-between;border-bottom:4px solid #d31145;padding-bottom:12px}.logo{background:#d31145;color:white;padding:12px;border-radius:10px;font-weight:900}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.k{border:1px solid #ddd;border-radius:10px;padding:10px}.k b{display:block;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border-bottom:1px solid #ddd;padding:6px;text-align:right}th:first-child,td:first-child{text-align:center}img{width:100%;margin:10px 0}.foot{font-size:9px;color:#666;margin-top:14px}@media print{button{display:none}}</style></head><body><div class="page"><div class="head"><div><h1 style="margin:0">รายงานสรุปกรมธรรม์</h1><div>${escapeHtml(p.insured||$('name')?.value||'ลูกค้า')}</div></div><div class="logo">AIA PLAN</div></div><p><b>${escapeHtml(p.product)}</b> • เลขที่กรมธรรม์ ${escapeHtml(p.number||'-')} • เริ่มอายุ ${p.startAge} ปี</p><div class="grid"><div class="k">เบี้ยรวม<b>${money(total('premium'))}</b></div><div class="k">เงินคืนระหว่างปีรวม<b>${money(total('cashback'))}</b></div><div class="k">ครบกำหนด<b>${money(total('maturity'))}</b></div><div class="k">ทุนชีวิตสูงสุด<b>${money(Math.max(0,...ys.map(x=>num(x.sumAssured))))}</b></div></div><img src="${img}"><table><thead><tr><th>อายุ</th><th>เบี้ย</th><th>เงินคืนระหว่างปี</th><th>ครบกำหนด</th><th>ทุนชีวิต</th></tr></thead><tbody>${ys.map(r=>`<tr><td>${r.age}</td><td>${money(r.premium)}</td><td>${money(r.cashback)}</td><td>${money(r.maturity)}</td><td>${money(r.sumAssured)}</td></tr>`).join('')}</tbody></table><div class="foot">เอกสารสรุปนี้จัดทำเพื่อประกอบการอธิบาย โปรดตรวจสอบรายละเอียด เงื่อนไข และผลประโยชน์จากเอกสารกรมธรรม์ฉบับจริงทุกครั้ง</div><button onclick="window.print()" style="margin-top:14px;padding:10px 16px;background:#d31145;color:white;border:0;border-radius:8px">พิมพ์ / บันทึกเป็น PDF</button></div></body></html>`);w.document.close()}
const oldOpen=window.openClient;window.openClient=async function(id){await oldOpen.apply(this,arguments);await loadPolicies()};
mount();
})();
